Repository kubevela/velaux, pull requests merged in 2022-07, with the labels that each got.

#562 Fix: show the error message of querying the logs
  src/pages/ApplicationInstanceList/components/ContainerLog/index.tsx
  src/pages/ApplicationLog/components/LogContainer/index.tsx
Labels: backport release-1.4

#564 Revert "Feat: add arm64 image build"
  .github/workflows/release.yaml
Labels: title-needs-formatting

#571 Fix: don't load provider list with default project
  src/pages/TargetList/components/TargetDialog/index.tsx
Labels: backport release-1.4

#575 Fix: the integration name is required
  src/pages/Integrations/components/CreateIntegrationDialog/index.tsx
Labels: backport release-1.4

#587 Fix: upgrade Nginx to 1.23 and fix CVE-2022-2068
  Dockerfile
  Dockerfile.local
Labels: backport release-1.4

#601 Fix: incorrect dex redirect URL
  src/pages/Login/index.tsx
Labels: backport release-1.5
